export const GET_COFFEE_REQUEST = 'GET_COFFEE_REQUEST';
export const GET_COFFEE_SUCCESS = 'GET_COFFEE_SUCCESS';
export const GET_COFFEE_FAIL = 'GET_COFFEE_FAIL';
export const CHANGE_COFFEE_COUNT = 'CHANGE_COFFEE_COUNT';